iboot-studio:
  show-server-url: true
  enum-dict:
    enabled: true
    scan-packages: com.novo.report.common.constant,com.novo.report.other.package
  log:
    aop:
      enabled: false
      pointcut:
        value: "execution(* com.novo.report.web.controller..*.*(..))"

spring:
  application:
    name: novo-report
  profiles:
    active: dev

  aop:
    auto: true  # 确保AOP自动配置启用
    proxy-target-class: true  # 使用CGLIB代理
  main:
    allow-circular-references: true  # 允许循环引用

server:
  port: 18080

sa-token:
  # 指定 Cookie 模式下自动填充 token 提交前缀
  cookie-auto-fill-prefix: true
  # 指定 token 提交时的前缀
  token-prefix: Bearer
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: simple-uuid
  # 是否打开自动续签（如果此值为 true，框架会在每次直接或间接调用 getLoginId() 时进行一次过期检查与续签操作）
  auto-renew: true
  # 是否输出操作日志
  is-log: true
  extension:
    enabled: true
    # 无需登录或者权限控制的资源
    excludes:
      - /
      - /api/iboot/sys/public/**
      - /api/iboot/auth/login
      - /api/iboot/auth/logout
      # // 排除静态资源目录（sa-token 不用加 serverContextPath 前缀但需要 / 开头）
      - /static/**
      - /assets/**
      - /iboot/**
      # // 排除根目录下的静态文件（sa-token 不用加 serverContextPath 前缀但需要 / 开头）
      - /*.js
      - /*.css
      - /*.html
      - /*.ico
      - /*.png
      - /*.jpg
      - /*.jpeg
      - /*.gif
      - /*.svg
      - /*.woff
      - /*.woff2
      - /*.ttf
      - /*.json
    demo-mode: false
    # 演示模式下运行操作的 非 GET 资源请求
    demo-mode-includes:
      - /api/iboot/auth/login
      - /api/iboot/auth/logout
    # 基础权限
    basic-permissions:
      # 用户获取自身信息（直接填权限码即可）
      - user/info
      - auth/getUserMenu

concept:
  download:
    source:
      cache:
        enabled: true #网络资源缓存是否启用
        #path: /source_cache #网络资源缓存路径，默认为 user.home/concept/download
        delete: true #下载结束后网络资源缓存是否删除
    compress:
      format: zip #压缩格式
      password: 123456 #压缩密码
      cache:
        enabled: true #压缩缓存是否启用
        #path: /compress_cache #压缩缓存路径，默认为 user.home/concept/download
        delete: true #下载结束后压缩缓存是否删除
    logger:
      enabled: true #日志总开关
      standard:
        enabled: false #标准流程日志是否启用
      progress:
        enabled: true #进度计算日志是否启用，包括加载进度，压缩进度，写入响应进度
        duration: 500 #进度计算日志输出间隔，ms
        percentage: true #进度计算日志是否使用百分比输出
      time-spent:
        enabled: true #时间计算日志是否启用

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/**.xml
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: true
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto
